services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_WEBSOCKET_URL='ws://backend:3000/ws'
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=dev
      - BACKEND_PORT=3000
      - DATABASE_URL=postgresql://postgres:password@db:5432/testcase_translator
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend/src:/app/src

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=testcase_translator
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: